### ISSUE TITLE
How do you deal with static generation?

### ISSUE THREAD

**Issue by denull0** [ElectricCodeGuy/SupabaseAuthWithSSR#8]
The supabase.js cache is causing all pages to be dynamic. Any idea how to get around that?

**Comment by ElectricCodeGuy** [comment]
There is no real solution to this atm since auth uses cookies and everything below the auth will be dynamic rendered.
Next 15 will support PPR. (https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering)

In current next 14 you should avoid making any auth related code inside the root layout, so cookies and headers, since everything nested inside this will be dynamic. This ,means that it will not be possible to have a header(navbar) or a footer that changes depending on if the user is signed in or not. (With is super common to have...). Use middleware to protect routes and redirect users depending on their session totken. 
Also use RLS with the anon key combined with generateStaticParams on routes where you want static content.

**Comment by denull0** [comment]
> There is no real solution to this atm since auth uses cookies and everything below the auth will be dynamic rendered. Next 15 will support PPR. (https://nextjs.org/docs/app/api-reference/next-config-js/partial-prerendering)
> 
> In current next 14 you should avoid making any auth related code inside the root layout, so cookies and headers, since everything nested inside this will be dynamic. This ,means that it will not be possible to have a header(navbar) or a footer that changes depending on if the user is signed in or not. (With is super common to have...). Use middleware to protect routes and redirect users depending on their session totken. Also use RLS with the anon key combined with generateStaticParams on routes where you want static content.

Thank you so much for your explanation! Supabase or Nextjs should've explained that the way you did. I was searching everywhere to understand what I was doing wrong.... Waiting for  Nextjs 15 would be the solution. 🙏
